from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from .SQLFuns import SQLFuns
from datetime import datetime


class Bin:
    com = {
        "Com000": "100",
        "Com002": "'" + datetime.now().strftime("%Y-%m-%d %H:%M:%S") + "'",
    }
    sqls = {
        "Bin000": ""
        + "SELECT 'GENRE^'||GENREID AS COL_KEY,'種別項目' AS COL_ITEM,GENRENAME AS COL_NAME,'' AS COL_REMARKS1,'' AS COL_REMARKS2,GENREVISIBLESTATUS AS COL_VISIBLESTATUS,strftime('%Y-%m-%d',GENREUPDATEDATE) AS COL_UPDATEDATE FROM T_GENRE WHERE GENREVISIBLESTATUS IN (:VISIBLESTATUS0,:VISIBLESTATUS1) "
        + "UNION "
        + "SELECT 'GOAL^'||GOALID,'目標項目',GOALNAME,'','',GOALVISIBLESTATUS,strftime('%Y-%m-%d',GOALUPDATEDATE) FROM T_GOAL WHERE GOALVISIBLESTATUS  IN (:VISIBLESTATUS0,:VISIBLESTATUS1) "
        + "UNION "
        + "SELECT 'PLAN^'||PLANID,'計画項目',PLANNAME,GOALNAME||'-'||PLANNAME,strftime('%Y%m%d', PLANSTARTDATE)||'-'||strftime('%Y%m%d', PLANENDDATE),PLANVISIBLESTATUS,strftime('%Y-%m-%d',PLANUPDATEDATE) FROM T_PLAN INNER JOIN T_GOAL USING(GOALID) WHERE PLANVISIBLESTATUS IN (:VISIBLESTATUS0,:VISIBLESTATUS1) "
        + "UNION "
        + "SELECT 'SCHEDULE^'||SCHEDULEID,'予定項目',strftime('%Y%m%d', SCHEDULEDATE),strftime('%H%M', SCHEDULESTARTTIME)||'-'||strftime('%H%M', SCHEDULEENDTIME),GOALNAME||'-'||PLANNAME,SCHEDULEVISIBLESTATUS,strftime('%Y-%m-%d',SCHEDULEUPDATEDATE) FROM T_SCHEDULE INNER JOIN T_PLAN USING(PLANID) INNER JOIN T_GOAL USING(GOALID) WHERE SCHEDULEVISIBLESTATUS IN (:VISIBLESTATUS0,:VISIBLESTATUS1) "
        + "UNION "
        + "SELECT 'TODO^'||TODOID,'復習項目',TODONAME,GOALNAME||'-'||PLANNAME,'',TODOVISIBLESTATUS,strftime('%Y-%m-%d',TODOUPDATEDATE) FROM T_TODO INNER JOIN T_PLAN USING(PLANID) INNER JOIN T_GOAL USING(GOALID) WHERE TODOVISIBLESTATUS IN (:VISIBLESTATUS0,:VISIBLESTATUS1)",
        "Bin001": ""
        + "SELECT 'GENRE^'||GENREID AS COL_KEY,'種別項目' AS COL_ITEM,GENRENAME AS COL_NAME,'' AS COL_REMARKS1,'' AS COL_REMARKS2,GENREVISIBLESTATUS AS COL_VISIBLESTATUS,strftime('%Y-%m-%d',GENREUPDATEDATE) AS COL_UPDATEDATE FROM T_GENRE WHERE GENREVISIBLESTATUS IN (:VISIBLESTATUS0,:VISIBLESTATUS1) AND GENRENAME LIKE :KEYWORD "
        + "UNION "
        + "SELECT 'GOAL^'||GOALID,'目標項目',GOALNAME,'','',GOALVISIBLESTATUS,strftime('%Y-%m-%d',GOALUPDATEDATE) FROM T_GOAL WHERE GOALVISIBLESTATUS IN (:VISIBLESTATUS0,:VISIBLESTATUS1) AND GOALNAME LIKE :KEYWORD "
        + "UNION "
        + "SELECT 'PLAN^'||PLANID,'計画項目',PLANNAME,GOALNAME||'-'||PLANNAME,strftime('%Y%m%d', PLANSTARTDATE)||'-'||strftime('%Y%m%d', PLANENDDATE),PLANVISIBLESTATUS,strftime('%Y-%m-%d',PLANUPDATEDATE) FROM T_PLAN INNER JOIN T_GOAL USING(GOALID) WHERE PLANVISIBLESTATUS IN (:VISIBLESTATUS0,:VISIBLESTATUS1) AND PLANNAME LIKE :KEYWORD"
        + "UNION "
        + "SELECT 'SCHEDULE^'||SCHEDULEID,'予定項目',strftime('%Y%m%d', SCHEDULEDATE),strftime('%H%M', SCHEDULESTARTTIME)||'-'||strftime('%H%M', SCHEDULEENDTIME),GOALNAME||'-'||PLANNAME,SCHEDULEVISIBLESTATUS,strftime('%Y-%m-%d',SCHEDULEUPDATEDATE) FROM T_SCHEDULE INNER JOIN T_PLAN USING(PLANID) INNER JOIN T_GOAL USING(GOALID) WHERE SCHEDULEVISIBLESTATUS IN (:VISIBLESTATUS0,:VISIBLESTATUS1) AND (GOALNAME LIKE :KEYWORD OR PLANNAME LIKE :KEYWORD) "
        + "UNION "
        + "SELECT 'TODO^'||TODOID,'復習項目',TODONAME,GOALNAME||'-'||PLANNAME,'',TODOVISIBLESTATUS,strftime('%Y-%m-%d',TODOUPDATEDATE) FROM T_TODO INNER JOIN T_PLAN USING(PLANID) INNER JOIN T_GOAL USING(GOALID) WHERE TODOVISIBLESTATUS IN (:VISIBLESTATUS0,:VISIBLESTATUS1) AND (GOALNAME LIKE :KEYWORD OR PLANNAME LIKE :KEYWORD)",
        "Bin002": ""
        + "SELECT 'GENRE^'||GENREID AS COL_KEY,'種別項目' AS COL_ITEM,GENRENAME AS COL_NAME,'' AS COL_REMARKS1,'' AS COL_REMARKS2,GENREVISIBLESTATUS AS COL_VISIBLESTATUS,strftime('%Y-%m-%d',GENREUPDATEDATE) AS COL_UPDATEDATE FROM T_GENRE WHERE GENREVISIBLESTATUS = :VISIBLESTATUS "
        + "UNION "
        + "SELECT 'GOAL^'||GOALID,'目標項目',GOALNAME,'','',GOALVISIBLESTATUS,strftime('%Y-%m-%d',GOALUPDATEDATE) FROM T_GOAL WHERE GOALVISIBLESTATUS = :VISIBLESTATUS "
        + "UNION "
        + "SELECT 'PLAN^'||PLANID,'計画項目',PLANNAME,GOALNAME||'-'||PLANNAME,strftime('%Y%m%d', PLANSTARTDATE)||'-'||strftime('%Y%m%d', PLANENDDATE),PLANVISIBLESTATUS,strftime('%Y-%m-%d',PLANUPDATEDATE) FROM T_PLAN INNER JOIN T_GOAL USING(GOALID) WHERE PLANVISIBLESTATUS = :VISIBLESTATUS "
        + "UNION "
        + "SELECT 'SCHEDULE^'||SCHEDULEID,'予定項目',strftime('%Y%m%d', SCHEDULEDATE),strftime('%H%M', SCHEDULESTARTTIME)||'-'||strftime('%H%M', SCHEDULEENDTIME),GOALNAME||'-'||PLANNAME,SCHEDULEVISIBLESTATUS,strftime('%Y-%m-%d',SCHEDULEUPDATEDATE) FROM T_SCHEDULE INNER JOIN T_PLAN USING(PLANID) INNER JOIN T_GOAL USING(GOALID) WHERE SCHEDULEVISIBLESTATUS = :VISIBLESTATUS "
        + "UNION "
        + "SELECT 'TODO^'||TODOID,'復習項目',TODONAME,GOALNAME||'-'||PLANNAME,'',TODOVISIBLESTATUS,strftime('%Y-%m-%d',TODOUPDATEDATE) FROM T_TODO INNER JOIN T_PLAN USING(PLANID) INNER JOIN T_GOAL USING(GOALID) WHERE TODOVISIBLESTATUS = :VISIBLESTATUS",
        "Bin003": ""
        + "SELECT 'GENRE^'||GENREID AS COL_KEY,'種別項目' AS COL_ITEM,GENRENAME AS COL_NAME,'' AS COL_REMARKS1,'' AS COL_REMARKS2,GENREVISIBLESTATUS AS COL_VISIBLESTATUS,strftime('%Y-%m-%d',GENREUPDATEDATE) AS COL_UPDATEDATE FROM T_GENRE WHERE GENREVISIBLESTATUS = :VISIBLESTATUS AND GENRENAME LIKE :KEYWORD "
        + "UNION "
        + "SELECT 'GOAL^'||GOALID,'目標項目',GOALNAME,'','',GOALVISIBLESTATUS,strftime('%Y-%m-%d',GOALUPDATEDATE) FROM T_GOAL WHERE GOALVISIBLESTATUS IN (:VISIBLESTATUS0,:VISIBLESTATUS1) AND GOALNAME LIKE :KEYWORD "
        + "UNION "
        + "SELECT 'PLAN^'||PLANID,'計画項目',PLANNAME,GOALNAME||'-'||PLANNAME,strftime('%Y%m%d', PLANSTARTDATE)||'-'||strftime('%Y%m%d', PLANENDDATE),PLANVISIBLESTATUS,strftime('%Y-%m-%d',PLANUPDATEDATE) FROM T_PLAN INNER JOIN T_GOAL USING(GOALID) WHERE PLANVISIBLESTATUS = :VISIBLESTATUS AND PLANNAME LIKE :KEYWORD"
        + "UNION "
        + "SELECT 'SCHEDULE^'||SCHEDULEID,'予定項目',strftime('%Y%m%d', SCHEDULEDATE),strftime('%H%M', SCHEDULESTARTTIME)||'-'||strftime('%H%M', SCHEDULEENDTIME),GOALNAME||'-'||PLANNAME,SCHEDULEVISIBLESTATUS,strftime('%Y-%m-%d',SCHEDULEUPDATEDATE) FROM T_SCHEDULE INNER JOIN T_PLAN USING(PLANID) INNER JOIN T_GOAL USING(GOALID) WHERE SCHEDULEVISIBLESTATUS IN (:VISIBLESTATUS0,:VISIBLESTATUS1) AND (GOALNAME LIKE :KEYWORD OR PLANNAME LIKE :KEYWORD) "
        + "UNION "
        + "SELECT 'TODO^'||TODOID,'復習項目',TODONAME,GOALNAME||'-'||PLANNAME,'',TODOVISIBLESTATUS,strftime('%Y-%m-%d',TODOUPDATEDATE) FROM T_TODO INNER JOIN T_PLAN USING(PLANID) INNER JOIN T_GOAL USING(GOALID) WHERE TODOVISIBLESTATUS = :VISIBLESTATUS AND (GOALNAME LIKE :KEYWORD OR PLANNAME LIKE :KEYWORD)",
    }

    def BinStorage(req):
        if req.method == "GET":
            KEYWORD = req.GET["KEYWORD"]
            sql = ""
            sqlParams = []
            if KEYWORD == "":
                sql = Bin.sqls["Bin000"]
                sqlParams = {
                    "VISIBLESTATUS0": "0",
                    "VISIBLESTATUS1": "2",
                }
            elif KEYWORD != "":
                sql = Bin.sqls["Bin001"]
                sqlParams = {
                    "VISIBLESTATUS0": "0",
                    "VISIBLESTATUS1": "2",
                    "KEYWORD": f"%{KEYWORD}%",
                }
            getData = {"getData": SQLFuns.SelectFun(sql, sqlParams)}
            return JsonResponse(getData)

    def BinRecycle(req):
        if req.method == "GET":
            KEYWORD = req.GET["KEYWORD"]
            sql = ""
            sqlParams = []
            if KEYWORD == "":
                sql = Bin.sqls["Bin002"]
                sqlParams = {
                    "VISIBLESTATUS": "0",
                }
            elif KEYWORD != "":
                sql = Bin.sqls["Bin003"]
                sqlParams = {
                    "VISIBLESTATUS": "0",
                    "KEYWORD": f"%{KEYWORD}%",
                }
            getData = {"getData": SQLFuns.SelectFun(sql, sqlParams)}
            return JsonResponse(getData)
